CREATE TABLE `ifund_all_info` (
  `COD_FUND` varchar(20) COLLATE utf8mb4_bin NOT NULL COMMENT '基金产品代码',
  `NAM_FUND` varchar(300) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '基金产品名称',
  `NAM_FUND_SHORT` varchar(200) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '基金产品简称',
  `COD_FUND_TYP` char(2) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '基金产品一级分类代码',
  `COD_FUND_STS` char(2) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '基金状态代码',
  `COD_FUND_RSK_LVL` char(2) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '产品风险等级：01-低，02-中低，03-中，04-中高，05-高',
  `COD_FUND_LIVE_STS` char(1) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '基金存续状态：0-在售，1-非在售',
  `COD_PURC_STS` char(1) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '基金产品购买状态',
  `COD_REDM_STS` char(1) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '基金产品赎回状态',
  `AMT_IDV_FST_SSCR_MIN` decimal(18,2) DEFAULT NULL COMMENT '对私首次认购下限金额',
  `AMT_IDV_FST_PURC_MIN` decimal(18,2) DEFAULT NULL COMMENT '对私申购首次购买额下限',
  `AMT_AIP_MIN` decimal(18,2) DEFAULT NULL COMMENT '最小定投额',
  `AMT_AIP_MAX` decimal(18,2) DEFAULT NULL COMMENT '最大定投额',
  `VLU_DCNT_PURC` decimal(16,8) DEFAULT NULL COMMENT '申购费率折扣（取自基金）',
  `VLU_DCNT_AIP` decimal(16,8) DEFAULT NULL COMMENT '定投费率折扣（取自基金）',
  `VLU_DCNT_SSCR` decimal(16,8) DEFAULT NULL COMMENT '认购费率折扣（取自基金）',
  `IND_PENS_FUND` char(1) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '养老金产品标识',
  `IND_IDX_FUND` char(2) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '指数基金产品标识',
  `IND_FOF` char(2) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '是否为FOF基金',
  `IND_ETF` char(2) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '是否为ETF基金',
  `COD_BONS_TYP` char(1) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '分红方式',
  `AMT_FUND_SCL` decimal(20,4) DEFAULT NULL COMMENT '基金规模（元）',
  `DATE_FUND_MKT` char(8) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '基金产品上市日期',
  `DATE_FUND_CRT` char(8) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '基金产品成立日期/基金合同生效日期',

  `VLU_MAX_DD_THIS_YEAR` decimal(20,8) DEFAULT NULL COMMENT '最大回撤（今年以来）',
  `VLU_MAX_DD_MTH` decimal(20,8) DEFAULT NULL COMMENT '最大回撤（近一月）',
  `VLU_MAX_DD_3_MTH` decimal(20,8) DEFAULT NULL COMMENT '最大回撤（近三月）',
  `VLU_MAX_DD_6_MTH` decimal(20,8) DEFAULT NULL COMMENT '最大回撤（近六月）',
  `VLU_MAX_DD_YEAR` decimal(20,8) DEFAULT NULL COMMENT '最大回撤（近一年）',
  `VLU_MAX_DD_2_YEAR` decimal(20,8) DEFAULT NULL COMMENT '最大回撤（近两年）',
  `VLU_MAX_DD_3_YEAR` decimal(20,8) DEFAULT NULL COMMENT '最大回撤（近三年）',
  `VLU_MAX_DD_YEAR_CRT` decimal(20,8) DEFAULT NULL COMMENT '最大回撤（成立以来）',
  `ID_VLU_MAX_DD_KIND_RANK_THIS_YEAR` decimal(20,4) DEFAULT NULL COMMENT '最大回撤同类排名（今年以来）',
  `ID_VLU_MAX_DD_KIND_RANK_MTH` decimal(20,4) DEFAULT NULL COMMENT '最大回撤同类排名（近一月）',
  `ID_VLU_MAX_DD_KIND_RANK_3_MTH` decimal(20,4) DEFAULT NULL COMMENT '最大回撤同类排名（近三月）',
  `ID_VLU_MAX_DD_KIND_RANK_6_MTH` decimal(20,4) DEFAULT NULL COMMENT '最大回撤同类排名（近六月）',
  `ID_VLU_MAX_DD_KIND_RANK_YEAR` decimal(20,4) DEFAULT NULL COMMENT '最大回撤同类排名（近一年）',
  `ID_VLU_MAX_DD_KIND_RANK_2_YEAR` decimal(20,4) DEFAULT NULL COMMENT '最大回撤同类排名（近二年）',
  `ID_VLU_MAX_DD_KIND_RANK_3_YEAR` decimal(20,4) DEFAULT NULL COMMENT '最大回撤同类排名（近三年）',
  `ID_VLU_MAX_DD_KIND_RANK_CRT` decimal(20,4) DEFAULT NULL COMMENT '最大回撤同类排名（成立以来）',

  `VLU_STD_THIS_YEAR` decimal(20,8) DEFAULT NULL COMMENT '标准差（波动率）（今年以来）',
  `VLU_STD_MTH` decimal(20,8) DEFAULT NULL COMMENT '标准差（波动率）（近一月）',
  `VLU_STD_3_MTH` decimal(20,8) DEFAULT NULL COMMENT '标准差（波动率）（近三月）',
  `VLU_STD_6_MTH` decimal(20,8) DEFAULT NULL COMMENT '标准差（波动率）（近六月）',
  `VLU_STD_YEAR` decimal(20,8) DEFAULT NULL COMMENT '标准差（波动率）（近一年）',
  `VLU_STD_2_YEAR` decimal(20,8) DEFAULT NULL COMMENT '标准差（波动率）（近二年）',
  `VLU_STD_3_YEAR` decimal(20,8) DEFAULT NULL COMMENT '标准差（波动率）（近三年）',
  `VLU_STD_YEAR_CRT` decimal(20,8) DEFAULT NULL COMMENT '标准差（波动率）（成立以来）',
  `ID_STD_KIND_RANK_THIS_YEAR` decimal(20,4) DEFAULT NULL COMMENT '标准差（波动率）同类排名（今年以来）',
  `ID_STD_KIND_RANK_MTH` decimal(20,4) DEFAULT NULL COMMENT '标准差（波动率）同类排名（近一月）',
  `ID_STD_KIND_RANK_3_MTH` decimal(20,4) DEFAULT NULL COMMENT '标准差（波动率）同类排名（近三月）',
  `ID_STD_KIND_RANK_6_MTH` decimal(20,4) DEFAULT NULL COMMENT '标准差（波动率）同类排名（近六月）',
  `ID_STD_KIND_RANK_YEAR` decimal(20,4) DEFAULT NULL COMMENT '标准差（波动率）同类排名（近一年）',
  `ID_STD_KIND_RANK_2_YEAR` decimal(20,4) DEFAULT NULL COMMENT '标准差（波动率）同类排名（近二年）',
  `ID_STD_KIND_RANK_3_YEAR` decimal(20,4) DEFAULT NULL COMMENT '标准差（波动率）同类排名（近三年）',
  `ID_STD_KIND_RANK_YEAR_CRT` decimal(20,4) DEFAULT NULL COMMENT '标准差（波动率）同类排名（成立以来）',

  `VLU_SHARP_THIS_YEAR` decimal(20,8) DEFAULT NULL COMMENT '夏普比率（今年以来）',
  `VLU_SHARP_MTH` decimal(20,8) DEFAULT NULL COMMENT '夏普比率（近一月）',
  `VLU_SHARP_3_MTH` decimal(20,8) DEFAULT NULL COMMENT '夏普比率（近三月）',
  `VLU_SHARP_6_MTH` decimal(20,8) DEFAULT NULL COMMENT '夏普比率（近六月）',
  `VLU_SHARP_YEAR` decimal(20,8) DEFAULT NULL COMMENT '夏普比率（近一年）',
  `VLU_SHARP_2_YEAR` decimal(20,8) DEFAULT NULL COMMENT '夏普比率（近二年）',
  `VLU_SHARP_3_YEAR` decimal(20,8) DEFAULT NULL COMMENT '夏普比率（近三年）',
  `VLU_SHARP_YEAR_CRT` decimal(20,8) DEFAULT NULL COMMENT '夏普比率（成立以来）',
  `ID_SHARP_KIND_RANK_THIS_YEAR` decimal(20,4) DEFAULT NULL COMMENT '夏普比率同类排名（今年以来）',
  `ID_SHARP_KIND_RANK_MTH` decimal(20,4) DEFAULT NULL COMMENT '夏普比率同类排名（近一月）',
  `ID_SHARP_KIND_RANK_3_MTH` decimal(20,4) DEFAULT NULL COMMENT '夏普比率同类排名（近三月）',
  `ID_SHARP_KIND_RANK_6_MTH` decimal(20,4) DEFAULT NULL COMMENT '夏普比率同类排名（近六月）',
  `ID_SHARP_KIND_RANK_YEAR` decimal(20,4) DEFAULT NULL COMMENT '夏普比率同类排名（近一年）',
  `ID_SHARP_KIND_RANK_2_YEAR` decimal(20,4) DEFAULT NULL COMMENT '夏普比率同类排名（近二年）',
  `ID_SHARP_KIND_RANK_3_YEAR` decimal(20,4) DEFAULT NULL COMMENT '夏普比率同类排名（近三年）',
  `ID_SHARP_KIND_RANK_CRT` decimal(20,4) DEFAULT NULL COMMENT '夏普比率同类排名（成立以来）',

  `VLU_FUND_NAV` decimal(20,8) DEFAULT NULL COMMENT '基金单位净值',
  `VLU_FUND_NAV_ACML` decimal(20,8) DEFAULT NULL COMMENT '基金累计净值',
  `AMT_TEN_THOU_EARN` decimal(20,6) DEFAULT NULL COMMENT '每万份基金单位收益',
  `VLU_SEVN_DAY_YEAR_RATE` decimal(20,6) DEFAULT NULL COMMENT '七日年化收益率',
  `VLU_ANNL_MEAN_YLD` decimal(28,6) DEFAULT NULL COMMENT '平均年化收益率',
  `VLU_NAV_GRTH_THIS_DAY` decimal(20,6) DEFAULT NULL COMMENT '收益率（今日）',
  `VLU_NAV_GRTH_THIS_WEEK` decimal(20,6) DEFAULT NULL COMMENT '收益率（本周以来）',
  `VLU_NAV_GRTH_THIS_MTH` decimal(20,6) DEFAULT NULL COMMENT '收益率（本月以来）',
  `VLU_NAV_GRTH_THIS_QTR` decimal(20,6) DEFAULT NULL COMMENT '收益率（本季以来）',
  `VLU_NAV_GRTH_THIS_YEAR` decimal(20,6) DEFAULT NULL COMMENT '收益率（本年以来）',
  `VLU_NAV_GRTH_WEEK` decimal(20,6) DEFAULT NULL COMMENT '收益率（一周）',
  `VLU_NAV_GRTH_MTH` decimal(20,6) DEFAULT NULL COMMENT '收益率（一个月）',
  `VLU_NAV_GRTH_3_MTH` decimal(20,6) DEFAULT NULL COMMENT '收益率（三个月）',
  `VLU_NAV_GRTH_6_MTH` decimal(20,6) DEFAULT NULL COMMENT '收益率（六个月）',
  `VLU_NAV_GRTH_YEAR` decimal(20,6) DEFAULT NULL COMMENT '收益率（一年）',
  `VLU_NAV_GRTH_2_YEAR` decimal(20,6) DEFAULT NULL COMMENT '收益率（两年）',
  `VLU_NAV_GRTH_3_YEAR` decimal(20,6) DEFAULT NULL COMMENT '收益率（三年）',
  `VLU_NAV_GRTH_4_YEAR` decimal(20,6) DEFAULT NULL COMMENT '收益率（四年）',
  `VLU_NAV_GRTH_5_YEAR` decimal(20,6) DEFAULT NULL COMMENT '收益率（五年）',
  `ID_RET_KIND_WEEK_RANK` decimal(20,4) DEFAULT NULL COMMENT '收益率同类排名（一周）',
  `ID_RET_KIND_MTH_RANK` decimal(20,4) DEFAULT NULL COMMENT '收益率同类排名（一个月）',
  `ID_RET_KIND_3_MTH_RANK` decimal(20,4) DEFAULT NULL COMMENT '收益率同类排名（三个月）',
  `ID_RET_KIND_6_MTH_RANK` decimal(20,4) DEFAULT NULL COMMENT '收益率同类排名（六个月）',
  `ID_RET_KIND_YEAR_RANK` decimal(20,4) DEFAULT NULL COMMENT '收益率同类排名（一年）',
  `ID_RET_KIND_2_YEAR_RANK` decimal(20,4) DEFAULT NULL COMMENT '收益率同类排名（两年）',
  `ID_RET_KIND_3_YEAR_RANK` decimal(20,4) DEFAULT NULL COMMENT '收益率同类排名（三年）',
  `ID_RET_KIND_4_YEAR_RANK` decimal(20,4) DEFAULT NULL COMMENT '收益率同类排名（四年）',
  `ID_RET_KIND_5_YEAR_RANK` decimal(20,4) DEFAULT NULL COMMENT '收益率同类排名（五年）',

  `VLU_EX_BM_WEEK` decimal(20,8) DEFAULT NULL COMMENT '超额收益（近一周）',
  `VLU_EX_BM_MTH` decimal(20,8) DEFAULT NULL COMMENT '超额收益（近一月）',
  `VLU_EX_BM_3_MTH` decimal(20,8) DEFAULT NULL COMMENT '超额收益（近三月）',
  `VLU_EX_BM_6_MTH` decimal(20,8) DEFAULT NULL COMMENT '超额收益（近六月）',
  `VLU_EX_BM_YEAR` decimal(20,8) DEFAULT NULL COMMENT '超额收益（近一年）',
  `VLU_EX_BM_2_YEAR` decimal(20,8) DEFAULT NULL COMMENT '超额收益（近二年）',
  `VLU_EX_BM_3_YEAR` decimal(20,8) DEFAULT NULL COMMENT '超额收益（近三年）',
  `VLU_EX_BM_5_YEAR` decimal(20,8) DEFAULT NULL COMMENT '超额收益（近五年）',
  `VLU_EX_BM_CRT` decimal(20,8) DEFAULT NULL COMMENT '超额收益（成立以来）',

  `NAM_MAGR_1` varchar(160) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '基金经理姓名',
  `COD_SEX_1` varchar(2) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '性别',
  `DAYS_OF_MAGR_1` int DEFAULT NULL COMMENT '基金从业天数',
  `AMT_MAGR_SCL_1` decimal(18,2) DEFAULT NULL COMMENT '管理规模（元）',
  `VLU_MAGR_TERM_RET_1` decimal(18,2) DEFAULT NULL COMMENT '在管期间任期回报（百分数）',
  `DATE_STRT_1` char(8) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '产品被基金经理开始管理的日期',
  `NAM_MAGR_2` varchar(160) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '基金经理姓名',
  `COD_SEX_2` varchar(2) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '性别',
  `DAYS_OF_MAGR_2` int DEFAULT NULL COMMENT '基金从业天数',
  `AMT_MAGR_SCL_2` decimal(18,2) DEFAULT NULL COMMENT '管理规模（元）',
  `VLU_MAGR_TERM_RET_2` decimal(18,2) DEFAULT NULL COMMENT '在管期间任期回报（百分数）',
  `DATE_STRT_2` char(8) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '产品被基金经理开始管理的日期',
  `NAM_MAGR_3` varchar(160) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '基金经理姓名',
  `COD_SEX_3` varchar(2) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '性别',
  `DAYS_OF_MAGR_3` int DEFAULT NULL COMMENT '基金从业天数',
  `AMT_MAGR_SCL_3` decimal(18,2) DEFAULT NULL COMMENT '管理规模（元）',
  `VLU_MAGR_TERM_RET_3` decimal(18,2) DEFAULT NULL COMMENT '在管期间任期回报（百分数）',
  `DATE_STRT_3` char(8) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '产品被基金经理开始管理的日期',
  `NAM_MAGR_4` varchar(160) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '基金经理姓名',
  `COD_SEX_4` varchar(2) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '性别',
  `DAYS_OF_MAGR_4` int DEFAULT NULL COMMENT '基金从业天数',
  `AMT_MAGR_SCL_4` decimal(18,2) DEFAULT NULL COMMENT '管理规模（元）',
  `VLU_MAGR_TERM_RET_4` decimal(18,2) DEFAULT NULL COMMENT '在管期间任期回报（百分数）',
  `DATE_STRT_4` char(8) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '产品被基金经理开始管理的日期',
  `NAM_MAGR_5` varchar(160) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '基金经理姓名',
  `COD_SEX_5` varchar(2) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '性别',
  `DAYS_OF_MAGR_5` int DEFAULT NULL COMMENT '基金从业天数',
  `AMT_MAGR_SCL_5` decimal(18,2) DEFAULT NULL COMMENT '管理规模（元）',
  `VLU_MAGR_TERM_RET_5` decimal(18,2) DEFAULT NULL COMMENT '在管期间任期回报（百分数）',
  `DATE_STRT_5` char(8) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '产品被基金经理开始管理的日期',

  `PCT_STOCK_ASSET` decimal(20,4) DEFAULT NULL COMMENT '股票资产分布',
  `PCT_CCY_ASSET` decimal(20,4) DEFAULT NULL COMMENT '货币资产分布',
  `PCT_BOND_ASSET` decimal(20,4) DEFAULT NULL COMMENT '债券资产分布',
  `PCT_OTHER_ASSET` decimal(20,4) DEFAULT NULL COMMENT '其他资产分布',
  `PCT_FUND_ASSET` decimal(20,4) DEFAULT NULL COMMENT '基金资产分布',
  `NAM_CMPY` varchar(200) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '基金公司名称',

  PRIMARY KEY (`COD_FUND`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_bin COMMENT='基金产品全量信息';